baseURL = "https://nugrhrizki.github.io/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Rizki Nugraha"
copyright = "MIT"
theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 2

[params]
subtitle = "Robotic - Linux - others"
favicon = "https://avatars.githubusercontent.com/u/46787877?s=400&u=0676039d1fde344fc8d5b950eac9034ef55a5b26&v=4"
enableReadingTime=true
enableAutoDarkMode = true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Rizki Nugraha"
description = "Rizki Nugraha Blog about Programming, Linux, Electrical and other things he is interested in"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
